# =========================================================
# PanStock API - application-prod.properties (PRODUCCIÓN)
# =========================================================

server.port=8080

# =========================================================
# BASE DE DATOS - PostgreSQL (Supabase)
# =========================================================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.lalssjeoomxvvvtwlvik
spring.datasource.password=${DB_PASSWORD}

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# =========================================================
# SEGURIDAD JWT
# =========================================================
application.security.jwt.secretKey=${JWT_SECRET}
application.security.jwt.expiration=86400000

# =========================================================
# ZONA HORARIA
# =========================================================
spring.jackson.time-zone=America/Argentina/Buenos_Aires

spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.defer-datasource-initialization=true