spring.datasource.url=jdbc:mariadb://localhost:3306/panstock_db
spring.datasource.username=panstock_user
spring.datasource.password=panstock123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=8081